language: generic
os: osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libglew-dev
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      sudo: false
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libglew-dev
          sources: *sources

install:
  - pip install --upgrade pip
  - pip install conan
  - conan install --build electric-fence --build libjpeg --build OpenSSL --build bzip2 --build libpng --build zlib --build freetype

script:
  - mkdir build
  - cd build && cmake ../ && cmake --build .
